all:
	# mac, arm64
	GOOS=darwin GOARCH=arm64 go build -o autobahn-testsuite-darwin-arm64 ./autobahn-testsuite.go 
	# linux amd64
	GOOS=linux GOARCH=amd64 go build -o autobahn-testsuite-linux-amd64 ./autobahn-testsuite.go 
