name: Go

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.20', '1.21']
    name: Go ${{ matrix.go }} sample

    steps:

    - name: Set up Go 1.20
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Build
      run: go build -v .

    - name: Test-386
      run: env GOARCH=386 go test -test.run=Test_Retry_sleep -v 
      #run: env GOARCH=386 go test -v -coverprofile='coverage.out' -covermode=count ./...
      
    - name: Test-Race
      run: env GOARCH=amd64 go test -v -race ./...

    - name: Test-amd64
      run: env GOARCH=amd64 go test -v -coverprofile='coverage.out' -covermode=count ./...

    - name: Upload Coverage report
      uses: codecov/codecov-action@v4.4.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.out
